alias IndexError = Error("IndexError")

trait Comparable:
    fn __eq__(self, other: Self) -> Bool:
        ...
    fn __ne__(self, other: Self) -> Bool:
        ...
    fn __lt__(self, other: Self) -> Bool:
        ...
    fn __le__(self, other: Self) -> Bool:
        ...
    fn __gt__(self, other: Self) -> Bool:
        ...
    fn __ge__(self, other: Self) -> Bool:
        ...

trait IdealCollectionElement(CollectionElement, Hashable, Stringable, Comparable):
    ...